### ISSUE TITLE
ログインに関する 2 つのコンポーネントの作成

### ISSUE THREAD

**Issue by kosukesaigusa** [kosukesaigusa/mottai-flutter-app#124]
## 概要

ログインに関する下記の 2 つのコンポーネントの作成する（Figma も確認すること）。

3 つのソーシャルログインボタンを表示するコンポーネント：

<img width="352" alt="image" src="https://github.com/kosukesaigusa/mottai-flutter-app/assets/13669049/f4c24010-764c-40cb-af24-d0bedec5f631">

`mottai_flutter_app/lib/auth/ui/sign_in_buttons.dart` に定義してください。その後、`AuthDependentBuilder` の `onUnAuthenticated` の `SignedOut()` の代わりに使用してください。

そして、ログインが必要な画面（チャットルーム画面など）で、正しく表示されていることを確認してください。

3 つのソーシャル連携状況を表すコンポーネント：

<img width="353" alt="image" src="https://github.com/kosukesaigusa/mottai-flutter-app/assets/13669049/d3af8169-09a4-43d8-b3c5-d73742e47db9">

ListView で 3 つ並べるだけでいいです。「連携済み・未連携」の部分は TextButton にしてください。ただし、実際に Cloud Firestore と通信する必要はないです、ハードコードで良いです。

後でこの Issue:

https://github.com/kosukesaigusa/mottai-flutter-app/issues/100

で使用します。

ナルン追記
ワーカーページとホストページ内にこのコンポーネントを記述してください！
すでにページ自体は仮作成が完了しているため、該当箇所をコンポーネント化するコードに変更お願いします。

LINE のアイコンは、おそらく `font_awesome_flutter` で見つかると思います。色などは LINE のアイコンの仕様を探してその通りの色にしてください。

## 方針・要件・詳細・完了の定義など

- 上記の実装が済んでいること
- Google, Apple, LINE のアイコンやサインインボタンの見た目がそれぞれのブランドの使用に従っていること（Google, Apple は従っていないと審査に通らないので）

## 補足

着手時には、[#mottai-app-issues](https://flutteruniv.slack.com/archives/C05HHFHGJSC) チャンネルにこの Issue を貼り付ける。

また、そうしたければ、要件の整理や進捗のつぶやきのようなことをそのスレッドに書く。Issue の内容や仕様に関する説明や認識合わせが必要な場合や、ペアプロを希望する場合はそのスレッド内で、然るべき人にメンションして話を進める。

**Comment by narunblog** [comment]
業務で実装したことあるんですが、ガイドラインがあるので公式サイト見ながら作成した方が良さげです！
参考になりそうな記事貼っておきます！
https://qiita.com/itominami/items/999e67245a3261244c3e

LINEだけ記事になかったので公式！
https://developers.line.biz/ja/docs/line-login/login-button/
