### ISSUE TITLE
LINE でログインできるようにする

### ISSUE THREAD

**Issue by kosukesaigusa** [kosukesaigusa/mottai-flutter-app#47]
## 概要

Google, Apple のログインの Issue:

https://github.com/KosukeSaigusa/mottai-flutter-app/issues/45

の兼ね合いもあるが、同様に LINE ログインもできるようにする。

Callable Functions の実装も必要。

次の記事とリポジトリを参考にする。

- https://zenn.dev/kosukesaigusa/articles/line-login-with-firebase-auth-by-custom-token
- https://github.com/KosukeSaigusa/firebase-auth-line-sign-in

LINE のチャネル ID などは @KosukeSaigusa に聞いて dart_define (Flutter) や .env (Functions) などで適切に管理する。

## 方針・要件・詳細・完了の定義など

- 上記の実装が済んでいること

## 補足

着手時には、[#mottai-app-issues](https://flutteruniv.slack.com/archives/C05HHFHGJSC) チャンネルにこの Issue を貼り付ける。

また、そうしたければ、要件の整理や進捗のつぶやきのようなことをそのスレッドに書く。Issue の内容や仕様に関する説明や認識合わせが必要な場合や、ペアプロを希望する場合はそのスレッド内で、然るべき人にメンションして話を進める。

**Comment by KuniMon-T** [comment]
@KosukeSaigusa 
こちらのイシューは、flutter歴4ヶ月くらいの初心者には難しいでしょうか？
他に興味があるのは、プッシュ通知と、仕事詳細ページのUIです。
おすすめがあれば教えてください。よろしくお願いします。
あと、git clone した後、数個のエラーが解消できず、まだビルドできていないので後で質問させていただきたいです。

**Comment by KosukeSaigusa** [comment]
@KuniMon-T 
Firebase Functions の方は私の過去の実装の参考情報がたくさんあるのと、クライアントの方はすでに Google, Apple の実装は済んでいるのでハードル低めだとは思います！

**Comment by KosukeSaigusa** [comment]
@KuniMon-T 

LINE のチャネル ID を設定する場所を作ったので、下記 Notion ページの確認をお願いします！

https://www.notion.so/kosukesaigusa/mottai-app-15d42b8473634021a361f4fb925276bc?pvs=4#cafc36170b0e4f72a42df0ee4b5d9384
