### ISSUE TITLE
プッシュ通知を受信できるようにする（クライアント実装のみ）

### ISSUE THREAD

**Issue by kosukesaigusa** [kosukesaigusa/mottai-flutter-app#48]
## 概要

プッシュ通知を受信・表示できる（foreground, background, terminated) ようにする。

下記の実装を参考にする。

https://github.com/KosukeSaigusa/spajam-2022-final/blob/main/lib/utils/firebase_messaging.dart

もし上記の実装を Riverpod に依存する部分とそうでない部分に分けられるのなら、Riverpod に依存しない部分だけを firebase_common パッケージに実装して、それを mottai_flutter_app で Riverpod を使って使用できるようにするのが良さそうかも（packages/mottai_flutter_app/lib/firestore_repository.dart でも似たようなことをしている）。

どのパッケージは Riverpod や Flutter に依存していけないのかを吟味すること。

Apple で実際に通知を受信するにははおそらく Apple Developer での設定が必要なので @KosukeSaigusa に言った上で、受信確認は Android で行っておくのが良いかも。

プッシュ通知をタップしてからの画面遷移などは未実装でも OK。

## 方針・要件・詳細・完了の定義など

- 上記の実装が済んでいること
- （可能なら）Android での受信確認ができていること

## 補足

着手時には、[#mottai-app-issues](https://flutteruniv.slack.com/archives/C05HHFHGJSC) チャンネルにこの Issue を貼り付ける。

また、そうしたければ、要件の整理や進捗のつぶやきのようなことをそのスレッドに書く。Issue の内容や仕様に関する説明や認識合わせが必要な場合や、ペアプロを希望する場合はそのスレッド内で、然るべき人にメンションして話を進める。

**Comment by RikitoNoto** [comment]
@KosukeSaigusa 
FCMの知識がなくて申し訳ないのですが、
こちらは #49 がなくてもテスト可能なんでしょうか？

**Comment by KosukeSaigusa** [comment]
@RikitoNoto 
たしかに実際の環境に近い動作確認をするには、その Issue が先に終わっていた方が良いですね🙏
ただ、FCM トークンをデバッグコンソールから取得して、それに対して Firebase Console からテストメッセージを打つことはできるので、「とりあえずちゃんと届く」の確認はできそうにも思います！
いずれにせよその Issue が着手可能になるようにドキュメントモデルの定義と flutterfire_gen の改善します！

**Comment by RikitoNoto** [comment]
@KosukeSaigusa 
かしこまりました！
そんなやり方があるんですね！
自分の現在のチケットが完了するまで、誰も着手しそうでなければやろうかなと思います！

**Comment by KosukeSaigusa** [comment]
@RikitoNoto 
ありがとうございます！もし私の作業起因で困るところあったら遠慮なく教えてください！

**Comment by kosukesaigusa** [comment]
とりあえずこの PR: https://github.com/kosukesaigusa/mottai-flutter-app/pull/114 を main にマージして、iOS のデバイスで FCM が受信（foreground, background, terminated) できることは確認した。

残件：

- Android でも届くことを確認（foreground, background, terminated)
- ページ遷移をできるようにする
- [やる気があれば] firebase_common にうまく移植する？（しなくてもいい気もしてきた）つまり、Riverpod 前提で書いているところから Riverpod に関係ない部分をうまく切り出して firebase_common に切り出し、アプリ側では必要に応じて Riverpod を使って使用できるようにする

**Comment by kosukesaigusa** [comment]
Android でも届くことも確認（foreground, background, terminated) できた。

Drawer から FCM トークンを表示できるので、FCM トークン周りの Flutter の実装と Firebase Functions での通知送信の実装が済むまでは、Firebase Console の Messaging からトークンを指定して直接送る。

**Comment by kosukesaigusa** [comment]
Android でも届くことも確認（foreground, background, terminated) できた。

Drawer から FCM トークンを表示できるので、FCM トークン周りの Flutter の実装と Firebase Functions での通知送信の実装が済むまでは、Firebase Console の Messaging からトークンを指定して直接送る。
