### ISSUE TITLE
画像詳細Viewで最大までズーム後、縮小ができない

### ISSUE THREAD

**Issue by RikitoNoto** [KosukeSaigusa/mottai-flutter-app#78]
## 概要
画像詳細View(dart_flutter_common/lib/src/image_detail_view.dart)を使用して、画像を表示し
最大まで拡大するとiOSの場合縮小ができなくなり、Androidの場合縮小はできるがスワイプを横方向に行わないと
縮小ができない。
おそらく原因はFlutterのInteractiveViewerにあり、画像を動かす処理のほうが、縮小の処理より優先されている可能性がある。

![mottai_issue](https://github.com/KosukeSaigusa/mottai-flutter-app/assets/56541594/dcc394bf-729b-4a47-8088-1fd841b438cc)

## 方針・要件・詳細・完了の定義など
iOSで縮小ができ、Androidでいかなる方向からスワイプしても縮小できること
photo_viewなどの別パッケージを使用して対応できるかも確認が必要。

## 補足

着手時には、[#mottai-app-issues](https://flutteruniv.slack.com/archives/C05HHFHGJSC) チャンネルにこの Issue を貼り付ける。

また、そうしたければ、要件の整理や進捗のつぶやきのようなことをそのスレッドに書く。Issue の内容や仕様に関する説明や認識合わせが必要な場合や、ペアプロを希望する場合はそのスレッド内で、然るべき人にメンションして話を進める。

**Comment by KosukeSaigusa** [comment]
> 画像を動かす処理のほうが、縮小の処理より優先されている可能性がある。

ちょうどタイムリーな話題で数日前に行った勉強会で似たような話が出ていたのでシェアします！（全く同じことかは分からない）

https://twitter.com/kumamo_tone/status/1683433656445177858

https://speakerdeck.com/kumamotone/suwaipudebi-zireruhua-xiang-viewerwozuo-ru?slide=10

**Comment by RikitoNoto** [comment]
@KosukeSaigusa 
ご連絡ありがとうございます！
イメージは全くこれと同じ感じですよね！
スワイプで画面が閉じるのもいいですね。。。
